import{a as m,i as f,S as h}from"./assets/vendor-D0cagnvz.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const p=async(t,r)=>{const a="48010442-005cbb84b5a65166ca3b031bb",o="https://pixabay.com/api/";try{const e=await m.get(o,{params:{key:a,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}});return{images:e.data.hits,totalHits:e.data.totalHits}}catch(e){return console.log("Error fetching images:",e),{images:[],totalHits:0}}},y=t=>{const r=document.querySelector(".gallery");if((t==null?void 0:t.length)===0){f.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}t.forEach(o=>{const e=document.createElement("div");e.classList.add("image-card"),e.innerHTML=`
      <a href="${o.largeImageURL}" class="gallery-link">
        <img src="${o.webformatURL}" alt="${o.tags}" class="gallery-image" />
      </a>
      <div class="image-info">
        <p><strong>Likes</strong> <span>${o.likes}</span></p>
        <p><strong>Views</strong> <span>${o.views}</span></p>
        <p><strong>Comments</strong> <span>${o.comments}</span></p>
        <p><strong>Downloads</strong> <span>${o.downloads}</span></p>
      </div>
    `,r.appendChild(e)}),new h(".gallery a").refresh()},b=()=>{document.querySelector(".loader").classList.add("active")},L=()=>{document.querySelector(".loader").classList.remove("active")};let l="",n=1,c=0;const g=document.querySelector(".form"),v=g.querySelector('input[type="text"]'),w=document.querySelector(".gallery"),i=document.querySelector("#load-more-button"),u=document.querySelector(".loader");g.addEventListener("submit",async t=>{if(t.preventDefault(),l=v.value.trim(),!l)return;n=1,b(),i.style.display="none",u.style.display="block",w.innerHTML="";const{images:r,totalHits:a}=await p(l,n);y(r),c=a,L(),u.style.display="none",i.style.display=n*15>=c?"none":"block"});i.addEventListener("click",async()=>{n++;const{images:t,totalHits:r}=await p(l,n);y(t),c=r,n*15>=c&&(i.style.display="none",alert("We're sorry, but you've reached the end of search results.")),S()});const S=()=>{const t=document.querySelector(".image-card").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})};
//# sourceMappingURL=index.js.map
